version: '3.4'

services:
  catalogdb: #database settings
    container_name: catalogdb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  basketdb:   #database settings
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"

  catalog.api: #api details
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017" # replace localhost with catalogdb
    depends_on:
      - catalogdb
    ports:
      - "8000:80" # forwarding port

  basket.api:   #api details
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80" # use diffent port for docker 

